name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - app/**
  workflow_dispatch: 

env:
    TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TEST_SECRET: ${{ secrets.KUBECONFIG }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: 'TEST'
        run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_SECRET}
          